# Generated by Django 4.2.7 on 2024-01-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internationals',
            fields=[
                ('InternationalId', models.AutoField(primary_key=True, serialize=False)),
                ('InternationalName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Locals',
            fields=[
                ('LocalId', models.AutoField(primary_key=True, serialize=False)),
                ('LocalName', models.CharField(max_length=500)),
            ],
        ),
    ]
